base_url = "https://spiny.pages.dev"
title = "spiny"
description = "A minimalist Zola theme"
compile_sass = false
minify_html = true
generate_feed = true
default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
# List pages on the index page
list_pages = true

# The author of the site, and all the articles
author = "elidhu"

# Default theme
default_theme = "light"

# Favicon
favicon = "logo.svg"

# Configure the navigation links in the Navbar
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/about", name_en = "/about/" },
  { url = "/journal", name_en = "/journal/" },
  { url = "/articles", name_en = "/articles/" },
]

# Configure the social links in the footer
[extra.social]
github = "https://github.com/elidhu"
email = "email@elidhu.com"
